/*globals define, _*/

/**
 * Generated by DecoratorGenerator
 */

define([
    'js/Decorators/DecoratorBase',
    './DiagramDesigner/petriNetDecorator.DiagramDesignerWidget',
    './PartBrowser/petriNetDecorator.PartBrowserWidget'
], function (DecoratorBase, petriNetDecoratorDiagramDesignerWidget, petriNetDecoratorPartBrowserWidget) {

    'use strict';

    var DECORATOR_ID = 'petriNetDecorator';

    function petriNetDecorator(params) {
        var opts = _.extend({loggerName: this.DECORATORID}, params);

        DecoratorBase.apply(this, [opts]);

        this.logger.debug('petriNetDecorator ctor');
    }

    _.extend(petriNetDecorator.prototype, DecoratorBase.prototype);
    petriNetDecorator.prototype.DECORATORID = DECORATOR_ID;

    /*********************** OVERRIDE DecoratorBase MEMBERS **************************/

    petriNetDecorator.prototype.initializeSupportedWidgetMap = function () {
        this.supportedWidgetMap = {
            DiagramDesigner: petriNetDecoratorDiagramDesignerWidget,
            PartBrowser: petriNetDecoratorPartBrowserWidget
        };
    };

    return petriNetDecorator;
});
